name: Verify Build

on:
  pull_request:
    branches:
      - master
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate Test Report
        run: ./gradlew :zenkey-sdk:generateJacocoTestReportJar
      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: zenkey-sdk/build/reports/
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: zenkey-sdk/build/jacoco/
      - name: Generate Documentation
        run: ./gradlew :zenkey-sdk:dokka
      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: zenkey-sdk/build/dokka